home_joint_config:
  j_torso_base: 0.0
  j_torso_1: 0.0
  j_arm_1_1: -0.5
  j_arm_1_2: -0.7
  j_arm_1_3: 0.5
  j_arm_1_4: -1.2
  j_arm_1_5: -0.5
  j_arm_1_6: 0.5
  j_arm_1_7: 0.5
  j_arm_2_1: 0.5
  j_arm_2_2: 0.7
  j_arm_2_3: -0.5
  j_arm_2_4: 1.2
  j_arm_2_5: 0.5
  j_arm_2_6: -0.5
  j_arm_2_7: -0.5


# used in: 
#        - `scripts/repair_klampt_motion_planner.py`
#        - 